INSERT INTO USERS(ID,FIRST_NAME,LAST_NAME,EMAIL_ID,PASSWORD,LOCKED) VALUES(1,'App User','1','app.user1@gmail.com','#$@$#%^^^@$@$@$#$@#$',0);
INSERT INTO USERS(ID,FIRST_NAME,LAST_NAME,EMAIL_ID,PASSWORD,LOCKED) VALUES(2,'App User','2','app.user2@gmail.com','#$@$#%^^^@$@$@$#$@#$',0);
INSERT INTO USERS(ID,FIRST_NAME,LAST_NAME,EMAIL_ID,PASSWORD,ROLE,LOCKED)
VALUES(3,'Admin User','1','admin.user@gmail.com','$2a$10$6/MT1dQVSAD4vO6F814myOEHwosx2LRGsp3gOGcvaWFgOrTgqNm0G','ADMIN',0);


INSERT INTO CATEGORY(ID,CATEGORY_NAME) VALUES (1,'Book');

INSERT INTO SUB_CATEGORY(ID,SUB_CATEGORY, CATEGORY_FK) VALUES (1,'History',1);
INSERT INTO SUB_CATEGORY(ID,SUB_CATEGORY, CATEGORY_FK) VALUES (2,'Romance',1);
INSERT INTO SUB_CATEGORY(ID,SUB_CATEGORY, CATEGORY_FK) VALUES (3,'Self Help',1);
INSERT INTO SUB_CATEGORY(ID,SUB_CATEGORY, CATEGORY_FK) VALUES (4,'Philosophy',1);
INSERT INTO SUB_CATEGORY(ID,SUB_CATEGORY, CATEGORY_FK) VALUES (5,'Management',1);
INSERT INTO SUB_CATEGORY(ID,SUB_CATEGORY, CATEGORY_FK) VALUES (6,'Auto Biography',1);
INSERT INTO SUB_CATEGORY(ID,SUB_CATEGORY, CATEGORY_FK) VALUES (7,'Religion',1);

INSERT INTO INVENTORY(ITEM,DESCRIPTION,PRICE,CATEGORY_FK,SUB_CATEGORY_FK,AVAILABLE) VALUES('Think & Win Like Dhoni','Item1 Description',75,1,3,1);
INSERT INTO INVENTORY(ITEM,DESCRIPTION,PRICE,CATEGORY_FK,SUB_CATEGORY_FK,AVAILABLE) VALUES('Udayar','Item2 Description',175,1,1,1);
INSERT INTO INVENTORY(ITEM,DESCRIPTION,PRICE,CATEGORY_FK,SUB_CATEGORY_FK,AVAILABLE) VALUES('Wings of Fire','Item3 Description',305,1,6,1);
INSERT INTO INVENTORY(ITEM,DESCRIPTION,PRICE,CATEGORY_FK,SUB_CATEGORY_FK,AVAILABLE) VALUES('Test Item4','Item4 Description',75,1,1,1);
INSERT INTO INVENTORY(ITEM,DESCRIPTION,PRICE,CATEGORY_FK,SUB_CATEGORY_FK,AVAILABLE) VALUES('Test Item5','Item5 Description',175,1,1,1);
INSERT INTO INVENTORY(ITEM,DESCRIPTION,PRICE,CATEGORY_FK,SUB_CATEGORY_FK,AVAILABLE) VALUES('Test Item6','Item6 Description',305,1,1,1);

INSERT INTO INVENTORY_IMAGES(ID,INVENTORY_FK,IMAGE_PATH) VALUES(1,1,'https://image.jpg');


INSERT INTO CART(ID,USER_FK) VALUES(1000,2);

INSERT INTO CART_ITEMS(ID,CART_FK,INVENTORY_FK,QUANTITY) VALUES(1001,1000,1,1);
INSERT INTO CART_ITEMS(ID,CART_FK,INVENTORY_FK,QUANTITY) VALUES(1002,1000,2,2);

INSERT INTO USER_INFO(ID, ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,STATE,ZIPCODE,DEFAULT_ADDRESS,USER_FK) VALUES(101,'AddressLine1','AddressLine2','City','State',123564,1,2);
INSERT INTO USER_INFO(ID, ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,STATE,ZIPCODE,DEFAULT_ADDRESS,USER_FK) VALUES(99,'AddressLine1','AddressLine2','City','State',123564,1,2);